#!/usr/bin/env osascript

set a to "Wunderlist"
set bid to id of application a
tell application a
reopen -- open a new default window if there are no windows
activate -- make frontmost
end tell

tell application "System Events" to tell process "Wunderlist"
try
set isfullscreen to value of attribute "AXFullScreen" of window 1
end try
end tell
